# @package _global_

# to execute this experiment run:
# python run.py experiment=default.yaml

seed: 12345
name: default

defaults:
  - /hydra: default.yaml
  - /logger: wandb.yaml
  - /callbacks: val-loss.yaml
  - /trainer: single-gpu.yaml
  - /model/network: image-val/classification-quantized-resnet18.yaml
  - /model/loss: base-classification.yaml
  - /model/optimizer: adam.yaml
  - /model/metrics: default-classification.yaml
  - /model/lr_scheduler: stepLR.yaml
  - /datamodule: default.yaml
  - /datamodule/dataset: deploy-aug21/default-img-val-001.000.000.yaml
  - /datamodule/dataset/transforms: object-detection/no-aug.yaml

trainer:
  max_epochs: 50

model:
  _target_: src.models.classification.ClassificationModel
