train:
  - _target_: src.data.transforms.XYWHToXYX2Y2
  - _target_: src.data.transforms.ConvertFromInts
  - _target_: src.data.transforms.Resize
    height: 300
    width: 300
  - _target_: src.data.transforms.RandomApply
    transforms:
      - _target_: src.data.transforms.RandomAffine
        degrees: 90
    p: 0.1
  - _target_: src.data.transforms.HorizontalFlip
    p: 0.1
  - _target_: src.data.transforms.VerticalFlip
    p: 0.1
  - _target_: src.data.transforms.RandomBlur
    p: 0.1
    strength: 1
  - _target_: src.data.transforms.PhotometricDistort
  - _target_: src.data.transforms.ToPercentCoords
  - _target_: src.data.transforms.ToTensor
val:
  - _target_: src.data.transforms.XYWHToXYX2Y2
  - _target_: src.data.transforms.ConvertFromInts
  - _target_: src.data.transforms.Resize
    height: 300
    width: 300
  - _target_: src.data.transforms.ToPercentCoords
  - _target_: src.data.transforms.ToTensor
test:
  - _target_: src.data.transforms.XYWHToXYX2Y2
  - _target_: src.data.transforms.ConvertFromInts
  - _target_: src.data.transforms.Resize
    height: 300
    width: 300
  - _target_: src.data.transforms.ToPercentCoords
  - _target_: src.data.transforms.ToTensor
