# @package _global_

# to execute this experiment run:
# python run.py experiment=default.yaml

seed: 12345
name: default

defaults:
  - /hydra: default.yaml
  - /logger: wandb.yaml
  - /callbacks: torchvision/yolo.yaml
  - /datamodule: object-detection/base-size-512-w-norm-003.yaml
  - /trainer: single-gpu.yaml
  - /model: defaults/torchvision.yaml
  - override /datamodule/dataset/transforms: object-detection/torchvision.yaml

trainer:
  max_epochs: 300

datamodule:
  batch_size: 16
  collate_fn: torchvision_dict_collate_without_background
  dataset:
    data_file: /data/ground-truth/jsons/v4.1.json
