# Sample config to merge counting model JSON (first) and Validation model JSON (second)
schema:
  info: {}
  images:
    id_key: id
    unique_keys:
      - file_path
    merge_strategy: unique_extend
  categories:
    id_key: id
    unique_keys:
      - name
      - supercategory
    merge_strategy: unique_extend
  box_annotations:
    id_key: id
    unique_keys:
      - image_id
      - category_id
      - bbox
      - bbox_score
    references:
      image_id:
        - images
        - id
      category_id:
        - categories
        - id
    merge_strategy: keep_first
  caption_annotations:
    id_key: id
    unique_keys:
      - image_id
      - category_id
      - caption
      - conf
    references:
      image_id:
        - images
        - id
      category_id:
        - categories
        - id
    merge_strategy: keep_second
  splits:
    references:
      image_id:
        - images
        - id
    merge_strategy: keep_first
