_target_: src.networks.ssd.SSD
feature_extractor:
  _target_: src.networks.ssd._vgg_extractor
  backbone_name: vgg16
  highres: True
  pretrained_backbone: True
anchor_generator:
  _target_: src.networks.ssd.DefaultBoxGenerator
  aspect_ratios: [[2], [2, 3], [2, 3], [2, 3], [2, 3], [2], [2]]
  steps: [8, 16, 32, 64, 128, 256, 512]
loss:
  _target_: src.networks.ssd.SSDDefaultLoss
img_size: [512, 512]
num_classes: 3
