defaults:
  - optimizer: AdamW/wd-1e-3.yaml
  - lr_scheduler: stepLR.yaml
  - network: ssd/cfvgg-size512-reducedfc.yaml

_target_: src.models.CFSSDNet
network:
  feature_extractor:
    backbone_name: vgg19
    pretrained_backbone: True
