defaults:
  - dataset: object-detection/v1.0.1.yaml
  - override dataset/transforms: object-detection/retina-net.yaml

_target_: src.data.base_datamodule.BaseDataModule
num_workers: 10
batch_size: 16
drop_last: False
pin_memory: True
