_target_: src.data.base_datamodule.BaseDataModule
num_workers: 10
batch_size: 32
shuffle: True
drop_last: False
pin_memory: True
sampler_config:
  train:
    _target_: src.data.CFSampler
    shuffle: True
  val:
    _target_: src.data.CFSampler
    shuffle: False
