train:
  - _target_: src.data.transforms.Resize
    height: 300
    width: 300
  - _target_: src.data.transforms.RandomApply
    p: 0.9
    transforms:
    - _target_: src.data.transforms.RandomAffine
      degrees: [30,65]   #Rotation in that range at random
      translate: [0.1,0.4] #Shift along (x,y) in ranges (-t[0],t[0]), (-t[1],t[1]) at random
      scale: [0.6, 0.8] #Scale in that range at random
      shear: [-0.5,0.5,-0.5,0.5] #Shear along x in (s[0],s[1]) and along y in (s[2],s[3]) at random
    - _target_: src.data.transforms.RandomPerspective
      p: 0.35
  - _target_: src.data.transforms.ConvertFromInts
  - _target_: src.data.transforms.ToTensor
val:
  - _target_: src.data.transforms.Resize
    height: 300
    width: 300
  - _target_: src.data.transforms.ConvertFromInts
  - _target_: src.data.transforms.ToTensor
test:
  - _target_: src.data.transforms.Resize
    height: 300
    width: 300
  - _target_: src.data.transforms.ConvertFromInts
  - _target_: src.data.transforms.ToTensor
